### PR TITLE
add meta.yml and generate README and CI configuration from templates

### PR DESCRIPTION
**Pull request by palmskog**
There is not really much point in testing a pure Coq library with several different versions of OCaml. This simplifies CI configuration to only test with each Coq version, and adds the usual badges, etc., to the README.

### CODE REVIEW

**Comment by palmskog** [comment]
@KevOrr do you mind if I merge this?

**Comment by KevOrr** [comment]
@palmskog sorry for the extremely late reply. I'm not sure how I never saw this PR until I got the notification it was merged.

Thank you for the changes, this really does simplify things. The `OPAMWITHTEST` environment variable is very helpful to avoid having to write a `custom_script` for docker-coq-action.

One question I have is what the effect of `+` in the recursive `make` invocations is. Afaict, the `+` only seems to have an effect if `make` is run with the `-n` flag, in which case it will only run the lines which have the `+` flag. Is that accurate?

Edit: ah, is the idea to recursively invoke `make`, but _also_ run it with `-n`, so that _all_ the commands that would have been run during a normal invocation would be printed, even if they reside in child Makefiles?

**Comment by palmskog** [comment]
@KevOrr the `+` stuff has to do with makefile parallelism, specifically to ensure we don't get this dreaded message with, say, 10-way parallelism:
```
warning: jobserver unavailable: using -j1. 
```

You can read more about it [on StackOverflow](https://stackoverflow.com/questions/60702726/warning-jobserver-unavailable-using-j1-add-to-parent-make-rule).

**Comment by KevOrr** [comment]
Thanks for the reference. I might be misreading, but it seems from that SO answer and the GNU Make docs that it links, that using the `MAKE` variable directly already tells Make that it's launching a child Make process and to set up the necessary IPC. But it doesn't cause any harm and if `MAKE` does not appear directly in the recipe but only indirectly through variable expansion, then the `+` becomes necessary to set up IPC. So I can see how it'd be a good habit to get into for any recursive invocation.

**Pull request merged**
